# -*- coding: utf-8 -*-
"""1 - Digite o horário atual - Lista 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vckrz1VS7_Qfuu4dnfSlc3Y-jOZV-aK5
"""

horas = int(input('Digite o horário atual:'))
if horas >= 18:
  print('Boa noite :D')
 
else:
  print('Bom dia!!')