# -*- coding: utf-8 -*-
"""2 - Digite o ano em que você nasceu - Lista 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVD_9NrG4Zx-DMN8I1ggPTzt9c7X2r4N
"""

year = int(input('Digite o ano em que você nasceu: '))
age = 2021 - year
if age >= 18:
  print('Voce tem {}, e você é maior de idade '.format(age))
if age < 18: 
  print('Voce tem {}, e você é menor de idade'.format(age))