# -*- coding: utf-8 -*-
"""2 - Verificação número impar ou par

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAeFCFWgibbqdKRF_YPoTOhJrDsyJrPP
"""

Number = int(input('Digite um número:'))
if(Number % 2 ==0):
  print('Seu número é par!!')
else:
  print('Esse número é impar!!')