# -*- coding: utf-8 -*-
"""3 - Digite a temperatura - Lista 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uJg-GQMsXIzHe2dbJ12D4t_jR1Np3Suk
"""

temp = int(input('Digite a temperatura: '))
if temp > 18:
  print('Está quente!')
else:
  print('Está frio!')