# -*- coding: utf-8 -*-
"""Bhaskara.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RSc2e7ZaR8iGTJn5YnJ7oo6f8F8RPez6
"""

import math

class Bhaskara:
  def __init__(self,a,b,c):
    self.a = a
    self.b = b
    self.c = c

  def delta(self):
    #b²-4ac
    return pow(self.b,2)-4*self.a*self.c

  def raiz_delta(self):
    return math.sqrt(delta)

  def array_x(self):
    x1 = (-self.b+raiz_delta)/2*self.a
    x2 = (-self.b-raiz_delta)/2*self.a

    if delta>0:
      return [x1,x2]
    else:
      return print("Insira valores válidos: Delta está negativo.")

  def resposta(self):
    #print(f"Resposta: o valor de x1 é igual a {array_x[0]} e o valor de x2 é igual {array_x[1]}")
    print(f"Bla{array_x[0]}")
    ,,+

print("Olá, digite os valores de ABC e diremos o valor da equação de Bhaskara")
a = int(input("Digite o valor do A: "))
b = int(input("Digite o valor do B: "))
c = int(input("Digite o valor do C: "))
bhaskara = Bhaskara(a,b,c)
print(bhaskara.resposta())