# -*- coding: utf-8 -*-
"""C para F - Lista 3 (2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11D5fzGFNlBq1JasIfEjENrsC5g_05ypZ
"""

c = int(input('Digite o valor em Celsius que vai ser convertido para Fahrenheit: '))
f = c*9/5+32
print (f)