# -*- coding: utf-8 -*-
"""Descubra o Raio - Lista 3 (1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVytn5aLjBNy-DD2EQvulrFU7OXmoa8H
"""

Pi = 3.14
r = int(input('Digite o raio:'))
c = Pi*r*r
print(c)