# -*- coding: utf-8 -*-
"""Digite o dia do seu anivesário

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsSNRPeCall-p-XodcvfaI72hMN7-Lz7
"""

dia = int(input('Digite o dia do seu anivesário: '))

if (dia==6):
  print('PARABÉNS!!')
else:
  print('Não ainda...')