# -*- coding: utf-8 -*-
"""Média Aritmética - Lista 3(4)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170oHPL5C39pj4eG2j0Gn50vvAFMIqXC7
"""

a = int(input('Digite a Primeira Nota:'))
b = int(input('Digite o Segunda Nota:'))
c = int(input('Digite o Terceira Nota:'))
mn = (a+b+c)/3
print('Sua média é:',mn)

