# -*- coding: utf-8 -*-
"""Trocar valor de variáveis - Lista 3 (3)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mcYwVR0LLqqZ9QMTijHBlUmIMdnki1dN
"""

a = int(input('Digite o valor A:'))
b = int(input('Digite o valor B:'))
c = a
a = b
b = c
print('Valor de A:',a)
print('Valor de B:',b)

